/**
 * Type-safe API wrappers generated from the OpenAPI schema.
 *
 * These functions wrap the raw axios client with proper TypeScript types
 * derived from `src/types/schema.d.ts` (auto-generated by openapi-typescript).
 *
 * Regenerate types whenever the backend changes:
 *   npm run openapi:sync
 */

import client from './client';
import type { components, operations } from '../types/schema';

// ── Convenience aliases ─────────────────────────────────────────────────────

export type Schemas = components['schemas'];

/** Extract the JSON response body of a successful (200) operation */
type Ok200<T extends { responses: { 200: { content: { 'application/json': unknown } } } }> =
  T['responses'][200]['content']['application/json'];

/** Extract the JSON request body of an operation */
type ReqBody<T extends { requestBody: { content: { 'application/json': unknown } } }> =
  T['requestBody']['content']['application/json'];

// ── Schema shorthand types ───────────────────────────────────────────────────

export type AuthSchema          = Schemas['AuthSchema'];
export type UpdateProfileSchema = Schemas['UpdateProfileSchema'];
export type AdminCourseSchema   = Schemas['AdminCourseSchema'];
export type AdminAssignmentSchema = Schemas['AdminAssignmentSchema'];
export type AnnotateSchema      = Schemas['AnnotateSchema'];
export type AiChatSchema        = Schemas['AiChatSchema'];
export type StudyCozeSchema     = Schemas['StudyCozeSchema'];

// ── Auth ─────────────────────────────────────────────────────────────────────

export const authApi = {
  login: (body: ReqBody<operations['login_api_login_post']>) =>
    client.post<Ok200<operations['login_api_login_post']>>('/login', body),

  register: (body: ReqBody<operations['register_api_register_post']>) =>
    client.post<Ok200<operations['register_api_register_post']>>('/register', body),

  logout: () =>
    client.post<Ok200<operations['logout_api_logout_post']>>('/logout'),

  getSession: () =>
    client.get<Ok200<operations['get_session_api_session_get']>>('/session'),

  updateProfile: (body: ReqBody<operations['update_profile_api_profile_update_post']>) =>
    client.post<Ok200<operations['update_profile_api_profile_update_post']>>('/profile/update', body),
};

// ── Admin ────────────────────────────────────────────────────────────────────

export const adminApi = {
  getUsers: () =>
    client.get<Ok200<operations['get_users_api_admin_users_get']>>('/admin/users'),

  addUser: (body: ReqBody<operations['add_user_api_admin_add_user_post']>) =>
    client.post<Ok200<operations['add_user_api_admin_add_user_post']>>('/admin/add_user', body),

  updateUser: (userId: string, body: ReqBody<operations['update_user_api_admin_update_user__user_id__put']>) =>
    client.put<Ok200<operations['update_user_api_admin_update_user__user_id__put']>>(`/admin/update_user/${userId}`, body),

  deleteUser: (userId: string) =>
    client.delete<Ok200<operations['delete_user_api_admin_delete_user__user_id__delete']>>(`/admin/delete_user/${userId}`),

  getRelationsOverview: () =>
    client.get<Ok200<operations['get_relations_overview_api_admin_relations_overview_get']>>('/admin/relations/overview'),

  createCourse: (body: ReqBody<operations['create_course_api_admin_courses_post']>) =>
    client.post<Ok200<operations['create_course_api_admin_courses_post']>>('/admin/courses', body),

  updateCourse: (courseId: string, body: ReqBody<operations['update_course_api_admin_courses__course_id__put']>) =>
    client.put<Ok200<operations['update_course_api_admin_courses__course_id__put']>>(`/admin/courses/${courseId}`, body),

  deleteCourse: (courseId: string) =>
    client.delete<Ok200<operations['delete_course_api_admin_courses__course_id__delete']>>(`/admin/courses/${courseId}`),

  addCourseStudent: (courseId: string, body: ReqBody<operations['add_course_student_api_admin_courses__course_id__students_post']>) =>
    client.post<Ok200<operations['add_course_student_api_admin_courses__course_id__students_post']>>(`/admin/courses/${courseId}/students`, body),

  removeCourseStudent: (courseId: string, studentId: string) =>
    client.delete<Ok200<operations['remove_course_student_api_admin_courses__course_id__students__student_id__delete']>>(`/admin/courses/${courseId}/students/${studentId}`),
};

// ── Grading ──────────────────────────────────────────────────────────────────

export const gradingApi = {
  annotate: (body: ReqBody<operations['request_annotation_api_ai_annotate_post']>) =>
    client.post<Ok200<operations['request_annotation_api_ai_annotate_post']>>('/ai/gateway/annotate', body),

  analyzeSubmission: (body: ReqBody<operations['analyze_submission_api_ai_analyze_post']>) =>
    client.post<Ok200<operations['analyze_submission_api_ai_analyze_post']>>('/ai/gateway/analyze', body),
};

// ── AI / Chat ─────────────────────────────────────────────────────────────────

export const aiApi = {
  chat: (body: ReqBody<operations['ai_chat_api_ai_chat_post']>) =>
    client.post<Ok200<operations['ai_chat_api_ai_chat_post']>>('/ai/chat', body),

  studyCoze: (body: ReqBody<operations['study_coze_api_ai_study_coze_post']>) =>
    client.post<Ok200<operations['study_coze_api_ai_study_coze_post']>>('/ai/study_coze', body),
};
