FROM node:20.19.5-alpine3.22 AS build

WORKDIR /web
ARG VITE_API_ROOT=
ENV VITE_API_ROOT=${VITE_API_ROOT}
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ ./
COPY data/ /data/
RUN npm run build

FROM nginx:1.29.2-alpine3.22
COPY deploy/nginx.conf /etc/nginx/templates/default.conf.template
COPY --from=build /web/dist /usr/share/nginx/html
EXPOSE 8080
