import asyncio
import base64
import os
import uuid

from fastapi import HTTPException
from google import genai
from google.genai import types

class GoogleImageGenerationMixin:
    async def _generate_image_google(
        self,
        prompt: str,
        output_directory: str,
        model: str,
    ) -> str:
        client = genai.Client()
        response = await asyncio.to_thread(
            client.models.generate_content,
            model=model,
            contents=prompt,
            config=types.GenerateContentConfig(response_modalities=["IMAGE"]),
        )

        response_parts = getattr(response, "parts", None)
        if not response_parts and getattr(response, "candidates", None):
            first_candidate = response.candidates[0] if response.candidates else None
            content = getattr(first_candidate, "content", None) if first_candidate else None
            response_parts = getattr(content, "parts", None) if content else None

        image_path = None
        for part in response_parts or []:
            if part.inline_data is not None:
                mime_type = getattr(part.inline_data, "mime_type", "") or ""
                extension = mime_type.split("/")[-1] if mime_type.startswith("image/") else "png"
                image_path = os.path.join(output_directory, f"{uuid.uuid4()}.{extension}")
                if hasattr(part, "as_image"):
                    part.as_image().save(image_path)
                else:
                    image_data = getattr(part.inline_data, "data", None)
                    if image_data is None:
                        continue
                    image_bytes = base64.b64decode(image_data) if isinstance(image_data, str) else image_data
                    with open(image_path, "wb") as image_file:
                        image_file.write(image_bytes)

        if not image_path:
            raise HTTPException(
                status_code=500,
                detail=f"No image generated by google {model}",
            )
        return image_path

    async def generate_image_gemini_flash(
        self,
        prompt: str,
        output_directory: str,
    ) -> str:
        return await self._generate_image_google(
            prompt,
            output_directory,
            "gemini-2.5-flash-image",
        )

    async def generate_image_nanobanana_pro(
        self,
        prompt: str,
        output_directory: str,
    ) -> str:
        return await self._generate_image_google(
            prompt,
            output_directory,
            "gemini-3-pro-image-preview",
        )


__all__ = ["GoogleImageGenerationMixin"]
